### ISSUE TITLE
Error running npm run prod

### ISSUE THREAD

**Issue by washedev** [greysonn/BagTrack#1]
```
Cannot find module:
import SettingsIcon from '@public/img/settings.svg';
import HomeIcon from '@public/img/home.svg';

```
```
Object is possibly 'null':
main.ts row 44 & 54
```
```
addsale.tx
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'AddSaleState'.
      No index signature with a parameter of type 'string' was found on type 'AddSaleState'.
```

**Comment by greysonn** [comment]
Hey, thanks for making this issue. These are just warnings thrown by the webpack compiler. Everything should still build correctly.

**Comment by greysonn** [comment]
If you run `npm run dev` instead these issues will be ignored. Looks like webpack won't create the build files unless there are no warnings thrown.

**Comment by washedev** [comment]
`npm run dev` this creates the problem, same errors

**Comment by greysonn** [comment]
`npm run dev` should throw the errors, but still build the dist/ files. If those files are created, you can `npm start` and everything will work normally.

**Comment by greysonn** [comment]
I've fixed all of the warnings webpack threw. You're now able to run `npm run prod` and build successfully.
