### ISSUE TITLE
Purchase Date Issues

### ISSUE THREAD

**Issue by chrisgreene18** [greysonn/BagTrack#5]
Some items display an invalid purchase date from StockX, or the date is completely off by even a few years. Just a heads up!

**Comment by greysonn** [comment]
Hey, thanks for making this issue. Unfortunately, whenever i'm porting sales over from stockx or goat, I have no idea when the actual user purchased the item themselves. However, stockx and goat both provide the initial release date of the item sold. That is what I use as the purchase date for those sales just as a guess. When I add the action to edit sales you will be able to go in and change the purchase date.
